# Generated by Django 5.2.7 on 2026-05-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='title',
            field=models.CharField(default='Global Site Content', max_length=200),
        ),
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.CreateModel(
            name='StoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file', models.FileField(upload_to='stories/media/')),
                ('caption', models.CharField(blank=True, max_length=280)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='content_app.story')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
