# Generated by Django 5.2.13 on 2026-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_sitecontent_is_active_story_updated_by_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='personal_title',
            field=models.CharField(default='Personal Biography', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='professional_title',
            field=models.CharField(default='Professional Biography', max_length=200),
        ),
    ]
