# Generated by Django 5.2.13 on 2026-05-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_app", "0004_sitecontent_personal_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecontent",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
